### ISSUE TITLE
.Net core version

### ISSUE THREAD

**Issue by LaevusDexter** [AnkiTools/AnkiSharp#2]
Add .net core version!

**Comment by Clement-Jean** [comment]
Hi, thanks for the proposal!

I would like to know what you would like to change for the .NET version.

Thank you again !

Clément jean
北语大学

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by LaevusDexter** [comment]
Just let it work! I tried to but it gives me errors when I open created deck and gives me errors at processing by trying to save created deck by other deck.

**Comment by Clement-Jean** [comment]
can you show me the errors please ?

**Comment by LaevusDexter** [comment]
https://1drv.ms/u/s!ApzVRTwv0DzE1XvA1s2Ro-OwhtS5
